# -*- coding: utf-8 -*-
"""Données structurées : sprints, leviers, mois, webinaire — JobTeaser x Sanofi."""

SPRINTS = [
 ("SPRINT 1","Sem. 1-2","Mois 1","Le dispositif tourne",
  "Campagnes live, tracking en place, premières impressions sur le compte.",
  "Audiences chargées · pixel &amp; UTM OK · 9 créas en diffusion · monitoring des signaux branché"),
 ("SPRINT 2","Sem. 3-4","Mois 1","Premiers apprentissages",
  "On lit les signaux : quelles créas sortent, quels pipelines résonnent.",
  "Top / flop créas identifiés · 1re liste de comptes chauds · interactions LinkedIn engagées"),
 ("SPRINT 3","Sem. 5-6","Mois 2","Intro &amp; mise en relation",
  "On entre <b>en relation</b> avec les cibles avant de leur écrire : demandes de connexion, intro par l'engagement, mise en relation via le réseau.",
  "Cibles en relation (taux d'acceptation) · liste nominative arrêtée · créas v2 en ligne"),
 ("SPRINT 4","Sem. 7-8","Mois 2","Outbound, webinaire &amp; bascule budget",
  "<b>Maintenant</b> qu'on est en relation : séquences LinkedIn + e-mail, webinaire IA &amp; biopharma, warm calls sur les leads.",
  "Taux de réponse séquences · inscrits &amp; participants · leads qualifiés · 1ers RDV · budget reventilé"),
 ("SPRINT 5","Sem. 9-10","Mois 3","Conversion",
  "Relances multicanales, gifting/invitations, envoi de ressources.",
  "RDV décideurs obtenus · taux de réponse relance · ressources envoyées"),
 ("SPRINT 6","Sem. 11-12","Mois 3","Décision",
  "On mesure et on tranche : on scale ou on met en pause.",
  "Coût par RDV · pipeline généré · <b>décision go / no-go</b> pour le mois 4"),
]

LEVERS = [
 ("Ads — Visibilité &amp; Content","Bulldozer","bdz",[3,3,2,1,1,1]),
 ("Ads — Conversion","Bulldozer","bdz",[1,1,2,3,3,3]),
 ("Itération créa","Bulldozer","bdz",[1,2,3,2,1,1]),
 ("Monitoring signaux d'affaires","Bulldozer (OS)","bdz",[2,3,3,3,3,3]),
 ("Interaction posts LinkedIn décideurs","JobTeaser · Alexis","jt",[2,3,3,3,3,3]),
 ("Intro &amp; mise en relation (cibles)","JobTeaser · Alexis","jt",[0,1,3,2,1,1]),
 ("Outbound LinkedIn","Alexis + Bulldozer","mix",[0,0,2,3,2,2]),
 ("Outbound e-mail","Bulldozer","bdz",[0,0,2,3,2,2]),
 ("Webinaire IA &amp; biopharma","Bulldozer + JobTeaser","mix",[0,0,1,3,1,1]),
 ("Warm call","JobTeaser · Alexis","jt",[0,0,0,2,3,3]),
 ("Envoi de ressources","Bulldozer","bdz",[0,0,1,1,3,3]),
 ("Gifting / invitation","JobTeaser","jt",[0,0,0,0,2,2]),
]

MONTHS = [
 ("MOIS 1","Préchauffage de l'audience &amp; apprentissage","~500 €","g",
  ["Compte Sanofi — large","RH &amp; Talent Acquisition","Marque employeur","Pipelines R&amp;D / Digital","DRH · VP Talent","Retargeting site"],
  ["cc_content_1","cc_content_2","cc_visi_1","cc_visi_2"],
  ["Toutes les campagnes tournent, <b>majorité du budget en Visibilité &amp; Content</b>",
   "Monitoring des signaux d'affaires : visite du site, changement de poste, nominations, annonces IA",
   "Interaction systématique avec les posts LinkedIn des décisionnaires et parties prenantes",
   "Apprentissage : on laisse tourner assez longtemps pour lire des tendances fiables"]),
 ("MOIS 2","Itération créa &amp; amélioration","~500 €","p",
  ["Engagés TOFU (retargeting)","Fonction RH resserrée","Inscrits webinaire","Comptes à signaux","Pipeline Digital / IA"],
  ["cc_conv_1","cc_conv_2","cc_visi_3","cc_content_3"],
  ["<b>Intro &amp; mise en relation</b> avec les cibles : demandes de connexion, intro par l'engagement et via le réseau — <b>avant</b> toute séquence",
   "<b>Activation de l'outbound</b> LinkedIn et e-mail, une fois la relation établie",
   "Reventilation du budget ads <b>vers la Conversion</b>",
   "<b>Webinaire IA &amp; biopharma</b> — recrutement des jeunes talents hybrides science + data (fin de mois)",
   "<b>Warm call</b> sur les leads en fin de mois"]),
 ("MOIS 3","Conversion &amp; décision","500 → 1 000 € (si probant)","g",
  ["Intent : visiteurs &amp; engagés webinaire","Décideurs nominatifs","Leads non convertis","Comptes globaux"],
  ["cc_conv_3","cc_visi_2","cc_content_1"],
  ["Relance e-mail + LinkedIn, <b>warm call sur l'intent</b> et sur les comptes globaux",
   "<b>Gifting</b> et/ou invitation (événement, petit-déjeuner)",
   "<b>Augmentation du budget ads</b> si les signaux sont bons",
   "Envoi de ressources personnalisées (livres blancs, replay, benchmarks)",
   "Warm call sur les cibles prioritaires"]),
]

WEEKS = [("S1",100,0),("S2",120,0),("S3",130,0),("S4",130,0),("S5",120,0),("S6",130,0),
         ("S7",130,0),("S8",130,0),("S9",150,1),("S10",220,1),("S11",250,1),("S12",270,1)]

WEBI = [
 ("wia","Recruter les profils hybrides science + data","Le paradoxe de l'IA à grande échelle",
  "Sanofi × OpenAI × Formation Bio (mai 2024) · investissement ~294 M$ hub IA Toronto.",
  "Décisionnaire (DRH, VP Talent) + Talent Acquisition",
  "Sécuriser les profils hybrides science + data avant la concurrence, en sourçant dès l'école.",
  [("Teaser · TOFU","Le profil hybride science + data. Le plus rare du marché.","On regarde pourquoi — et ce qui marche vraiment en biopharma. Webinaire, 45 min.","Je réserve ma place","Néon mint/violet, ADN + réseau de données"),
   ("Inscription · MOFU","IA &amp; biopharma : la méthode qui marche","Table ronde avec un acteur biopharma, une école d'ingénieurs/data et JobTeaser.","Je m'inscris","Mockup salle de webinaire + 3 portraits intervenants"),
   ("Last call · BOFU","Dernières places — jeudi 11h.","45 min pour repartir avec une méthode de sourcing science + data.","Réserver / recevoir le replay","Compte à rebours néon, fond sombre, CTA vert")]),
 ("wec","Early Careers : quatre pipelines, un seul vivier","Cinq pipelines, une marque",
  "Programme Early Careers 2026 : R&amp;D, Digital, Commercial, Manufacturing &amp; Supply Chain.",
  "Early Careers / Campus + Talent Acquisition",
  "Mutualiser le sourcing amont sur les 4 pipelines sans diluer l'évaluation spécialisée.",
  [("Teaser · TOFU","4 pipelines Early Careers. Une seule marque employeur ?","Ce que ça change vraiment de mutualiser le sourcing en amont. Webinaire, 45 min.","Je réserve ma place","4 chemins convergents néon, chiffre en très grand"),
   ("Inscription · MOFU","Le sourcing Early Careers qui marche, pipeline par pipeline","Retour d'expérience : couverture campus, ciblage filière, conversion.","Je m'inscris","Réseau écoles néon + badge « cas concret »"),
   ("Last call · BOFU","Jeudi 11h — 45 min, 4 pipelines, 1 méthode.","Comment construire un vivier Early Careers cohérent sans fusionner l'évaluation.","Réserver / recevoir le replay","Compte à rebours, CTA vert")]),
 ("wgw","Le virage IA comme fenêtre de recrutement","Premier biopharma piloté par l'IA",
  "Positionnement « R&amp;D-Driven and AI-Powered Biopharmaceutical Company ».",
  "DRH / VP Talent / Direction R&amp;D",
  "Traduire un positionnement institutionnel en plan de sourcing concret.",
  [("Teaser · TOFU","Premier biopharma piloté par l'IA. Qui va le construire ?","L'ambition est affichée. Le plan de sourcing, pas encore. Webinaire, 45 min.","Je réserve ma place","ADN + réseau neuronal néon, trajectoire ascendante"),
   ("Inscription · MOFU","De l'ambition IA au plan de recrutement","Comment traduire un positionnement stratégique en plan de sourcing par filière.","Je m'inscris","Schéma avant/après virage IA"),
   ("Last call · BOFU","Dernières places.","45 min pour repartir avec une grille de conversion positionnement → recrutement.","Réserver / recevoir le replay","Compte à rebours + CTA")]),
 ("wemp","Marque employeur biopharma : sortir de l'ombre du Digital","Le pipeline Manufacturing oublié",
  "5 M+ de jeunes sur JobTeaser · le pipeline Manufacturing &amp; Supply Chain, absent des annonces IA.",
  "DRH / Marque employeur",
  "Rééquilibrer l'exposition de marque entre les 4 pipelines Early Careers.",
  [("Teaser · TOFU","Vos 4 pipelines. Vos 4 niveaux de visibilité, très inégaux.","Webinaire : rééquilibrer la marque employeur pipeline par pipeline. 45 min.","Je réserve ma place","Contraste ligne de production terne → néon vivant"),
   ("Inscription · MOFU","Comment le Manufacturing peut rattraper le Digital","Positionnement, preuves, canaux : la méthode et les benchmarks du secteur.","Je m'inscris","Podium/comparatif pipelines, néon"),
   ("Last call · BOFU","Jeudi 11h — dernières places.","Repartez avec la grille de préférence employeur appliquée à vos 4 pipelines.","Réserver / recevoir le replay","Compte à rebours + CTA")]),
 ("wcout","Le coût caché d'un poste IA/data non pourvu","L'argument budget",
  "294 M$ investis en capacités IA — combien en capacités humaines ?",
  "Décisionnaire (DRH, Finance RH)",
  "Chiffrer l'inaction pour débloquer un budget de sourcing dédié.",
  [("Teaser · TOFU","294 M$ en IA. Combien en talents pour la faire tourner ?","Webinaire : le calcul que personne ne fait en biopharma. 45 min.","Je réserve ma place","Balance capital/capital humain, chiffre dominant"),
   ("Inscription · MOFU","Le business case du recrutement IA/data anticipé","Modèle de raisonnement, benchmarks secteur, comment le présenter à votre direction financière.","Je m'inscris","Tableau/dashboard néon, allure « note ROI »"),
   ("Last call · BOFU","Dernières places — repartez avec le modèle de calcul.","45 min pour transformer une intuition RH en ligne budgétaire.","Réserver / recevoir le replay","Compte à rebours + CTA")]),
 ("wsource","Sourcer les profils hybrides sur les campus","800+ écoles, filière par filière",
  "800 écoles &amp; universités partenaires · 250 000 recruteurs · 5 M d'étudiants (JobTeaser).",
  "Talent Acquisition / sourcing",
  "Construire un plan campus par filière (pharmacie, data, ingénierie) plutôt qu'une présence dispersée.",
  [("Teaser · TOFU","800 écoles. Vous en couvrez combien pour vos profils hybrides ?","Webinaire : bâtir un plan campus qui alimente vos viviers critiques. 45 min.","Je réserve ma place","Carte Europe néon avec points écoles"),
   ("Inscription · MOFU","Le plan campus, filière par filière","Quelles écoles pour quels métiers biopharma/IA, à quel moment, avec quels formats.","Je m'inscris","Grille filières × métiers, style éditorial"),
   ("Last call · BOFU","Jeudi 11h — dernières places.","Repartez avec votre short-list d'écoles prioritaires.","Réserver / recevoir le replay","Compte à rebours + CTA")]),
]
